### ISSUE TITLE
issue loading the library via Rstudio

### ISSUE THREAD

**Issue by lcampb23** [mkshaw/r2mlm#24]
I downloaded the package, but when I try to load the library I get this error message: "Error in library((r2mlm)) : 'package' must be of length 1". This could be a problem of my own making, but wanted to ask to see if this is an issue with the package. Thank you.

**Comment by lcampb23** [comment]
So sorry--was a user error (facepalm).

**Comment by lcampb23** [comment]
Thanks! First time trying to use it. two issues:
1) would not run with missing data. So, I used the mice package to fix that.
2) get error that only the grouping variable can be a factor (but it is the only factor variable). Simple model--1 numeric DV and 1 numeric IV (that's it), with the IV nested within "person". So, I changed "person" to a numeric variable, but I still get the same error (even though all variables in model are numeric). I see on github that you have listed this issue as a bug, so I guess I will wait to there is an update and try again.

I do look forward to making use of this package though! I run a lot of MLMs with diary data etc..

Professor, Department of Psychology
University of Western Ontario
London, ON, Canada, N6A 5C2
(519) 661-2111 x84904<tel:%28519%29%20661-2111%20x84904>

Web<http://publish.uwo.ca/~lcampb23> || CV<http://publish.uwo.ca/~lcampb23/CV.pdf> || Google Scholar<https://scholar.google.ca/citations?user=E80DLosAAAAJ&hl=en> || Twitter<https://twitter.com/LorneJCampbell> || OSF<https://osf.io/sa9im/> || Blog<https://lornecampbell.org/>
________________________________

**Comment by mkshaw** [comment]
Yes, I've added this missing data issue, too, here: https://github.com/mkshaw/r2mlm/issues/23. Can you elaborate on how you used mice to solve the problem?

**Comment by lcampb23** [comment]
I simply used mice to impute values when they were missing, so the data set no longer has any missing values. I hope that makes sense.

Professor, Department of Psychology
University of Western Ontario
London, ON, Canada, N6A 5C2
(519) 661-2111 x84904<tel:%28519%29%20661-2111%20x84904>

Web<http://publish.uwo.ca/~lcampb23> || CV<http://publish.uwo.ca/~lcampb23/CV.pdf> || Google Scholar<https://scholar.google.ca/citations?user=E80DLosAAAAJ&hl=en> || Twitter<https://twitter.com/LorneJCampbell> || OSF<https://osf.io/sa9im/> || Blog<https://lornecampbell.org/>
________________________________

**Comment by mkshaw** [comment]
It does; thanks!
