### ISSUE TITLE
Is it possible to suppress the bar plots? and is it possible to get negative delta R^2 for the total?

### ISSUE THREAD

**Issue by xliu0806** [mkshaw/r2mlm#46]
Thanks for the package! 

Is it possible to suppress the bar plots in the output of the function r2mlm (or r2mlm_comp)? (I try to incorporate the results into a report automatically but don't want to include the bar plots).

Another question may not be related to the function here, but any advice?  

I have two nested models: Model A with one level-2 predictor, Model B = Model A + two more level 2-predictors, random intercepts in both models. The Delta R^2 of f2 for 'between' is 51%, delta R^2 of f2 for 'total' is 9%, but the delta R^2 of (fvm) for 'total' is -.0004% (maybe we can treat it as zero). I am just curious (wondering) what does this mean?  Does it mean that by including two more level-2 predictors in the model, although the two additional predictors help explain 9% total variance, the overall MLM model itself does not help explain any additional total variance (or even less)?

Thanks!
XD

**Comment by xliu0806** [comment]
I don't have level-1 predictor in the model.

**Comment by mkshaw** [comment]
There's no current way to suppress the bar plots, but I'll incorporate that into the next version of the package. Thank you for the suggestion!

re: the negative delta for fvm, I asked my collaborator Jason Rights, and he said the following:

> The increase in variance explained by the added level-2 predictors is accompanied with an equivalent decrease in the variance accounted for by the random intercept variance (because the level-2 predictors in the full model are explaining the residual between-cluster variance in the reduced model). As such, when looking at the conditional total R-squared, the net difference is 0. We talked about this in Rights & Sterba (2020), and explain why it thus doesn't make sense to quantify the impact of level-2 predictors using the conditional total R-squared (or the total R2_fvm), and that researchers should instead use the delta f2s specifically. 

For an illustration of this exact thing, see Figure 4 in Rights & Sterba (2020): [Rights, J. D., & Sterba, S. K. (2020). New recommendations on the use of R-squared differences in multilevel model comparisons. Multivariate Behavioral Research, 55, 568-599.](https://psycnet.apa.org/record/2019-59052-001) Hope that helps!

**Comment by xliu0806** [comment]
Excellent! thanks! 
and thanks for the Rights & Sterba (2020) reference!

**Comment by mkshaw** [comment]
@xliu0806 Just a heads up that I've integrated optional bar graph output into the development version of the package (which you can install with `devtools::install_github("mkshaw/r2mlm")`. It'll eventually be in the CRAN version when I submit the next version. The argument to `r2mlm` is called bargraph, it defaults to true (i.e., yes a bar graph will output), set it to false for no graphical output. Let me know if it works alright for you, and thanks again for the suggestion!
