### ISSUE TITLE
Error in t(v) %*% psi : non-conformable arguments

### ISSUE THREAD

**Issue by bbachilles** [mkshaw/r2mlm#47]
Hello, 

Thank you for your work on this package. I am trying to run the r2mlm function after a 3-level model. Doing so gives me the error in the subject. Code is below:

```library(haven) 
library(lme4) 
achieve <- read_dta("https://www.stata-press.com/data/mlmus3/achievement.dta")
m3levc <- lmer(math ~ female + black + hispanic + retained + (1| school) + (1 | child), achieve) 
r2mlm(m3levc)
```
```

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)
```

Thanks!

**Comment by mkshaw** [comment]
Hello! The package currently only works for two-level models; a three-level option, at least for manual entry, is on the way soon!
