### ISSUE TITLE
Bargraph from "r2mlm" function doesn't fully fit, and legend overlaps with x-axis titles

### ISSUE THREAD

**Issue by jpsnijder** [mkshaw/r2mlm#54]
Hi Mairead,

first of course thank you for your work on this. It is very helpful :) 

I have an issue with getting the plot to play nice. see images below. 
No matter how I drag/size the plot I can't get it to come out nice. My screen resolution is 2560 * 1440.
Maintain aspect ration on/off doesn't matter. R/Rstudio are updated.
Saving as image, copy to clipboard, none of it gives me a nice plot..

Any ideas here?

![image](https://user-images.githubusercontent.com/42057767/157632605-fbcbf0d2-13bd-4064-926e-6eb6bb6df050.png)
![image](https://user-images.githubusercontent.com/42057767/157632666-cfc3ec91-92fd-4389-99f2-74d62e3183b9.png)

**Comment by jpsnijder** [comment]
Sorry I didn't do better research! I found the code right in the example right here!
For others:
# Adjust plot margins
par(mar = c(6.75, 10.5, 2.625, 10.5))

**Comment by mkshaw** [comment]
Hi @jpsnijder thank you for your kind words about the package and that's it exactly: the plot margins just have to be changed around until the graph fits decently. Glad you resolved the problem! :)
