### ISSUE TITLE
Return numeric values in $Decomposition

### ISSUE THREAD

**Issue by nicebread** [mkshaw/r2mlm#55]
Could you return numeric values (in a data frame) for $Decomposition and $R2s?
I wanted to round the values before printing (for teaching), but with the hard-coded characters this is difficult. Furthermore, numeric values allow downstream computations.

Thanks!

**Comment by mkshaw** [comment]
Thanks for the suggestion!

**Comment by mkshaw** [comment]
@nicebread I'm in the process of releasing 0.3.2, which will feature numeric output. Should be out in the next few days!
