### ISSUE TITLE
CRAN update

### ISSUE THREAD

**Issue by IndrajeetPatil** [mkshaw/r2mlm#57]
Follow up on https://github.com/mkshaw/r2mlm/issues/52

@mkshaw Any plans to update the package on CRAN soon?

I can't archive my _broomExtra_ package on CRAN until _r2mlm_ has been updated on CRAN to not rely on it.

**Comment by mkshaw** [comment]
@IndrajeetPatil Sorry about that! I'll update today or tomorrow.

**Comment by mkshaw** [comment]
@IndrajeetPatil submitted the package to CRAN, hopefully it will be accepted soon and the dependency on *broomExtra* removed.

**Comment by IndrajeetPatil** [comment]
Cool, thanks!
