### ISSUE TITLE
r2mlm3_manual() Bug in Code?

### ISSUE THREAD

**Issue by IvoRollmann** [mkshaw/r2mlm#62]
Hello, 

I am currently using the r2mlm3_manual() function to calculate the expained variance of a non clustermean centered Model.

I get the error the following error message:

'Error in if (data[i, "schoolid"] == clus3) { : argument is of length zero'

Looking at the source code of the function I found that the following passage:

for (clus3 in seq(max(as.numeric(data[, l3clusterID_noncmc])))) {
            for (i in seq(nrow(data))) {
                if (data[i, "schoolid"] == clus3) {
                  if (is.null(allfixedcovs_noncmc) == F) {
                    for (ncov in seq(length(allfixedcovs_noncmc))) {
                      data_fixed_centered[i, paste0("p", ncov, 
                        "_l3")] <- mean(data_temp[which(data_temp[, 
                        l3clusterID_noncmc] == clus3), allfixedcovs_noncmc[ncov]], 
                        na.rm = T)
                    }

Which leads to the error. A few lines above this code is a similar passage for the level 2 cluster:

for (clus2 in seq(max(as.numeric(data[, l2clusterID_noncmc])))) {
            for (i in seq(nrow(data))) {
                if (data[i, l2clusterID_noncmc] == clus2) {
                  if (is.null(allfixedcovs_noncmc) == F) {
                    for (ncov in seq(length(allfixedcovs_noncmc))) {
                      data_fixed_centered[i, paste0("p", ncov, 
                        "_l1")] <- data[i, allfixedcovs_noncmc[ncov]] - 
                        mean(data_temp[which(data_temp[, l2clusterID_noncmc] == 
                          clus2), allfixedcovs_noncmc[ncov]], 
                          na.rm = T)

In the level 2 cluster pasage it clearly states data[i, l2clusterID_noncmc], while the level 3 cluster passage asked for an undefined
data[i, "schoolid"].
In the complete function "schoolid" is not defined.

Could that be a typo in the code? 

Kind regards,
Ivo Rollmann

**Comment by IvoRollmann** [comment]
Short updated, 

i replaced the "shoolid" with l3clusterID_noncmc and the code worked as intended.
It really is just a typo, which should be removed in the package.

**Comment by mkshaw** [comment]
Thanks for pointing that out, Ivo! I'll fix it this week.

**Comment by mkshaw** [comment]
@IvoRollmann fixed it in version 0.3.3, now on CRAN.
