### ISSUE TITLE
bargraphs in r2mlm_comp(model1, model2)

### ISSUE THREAD

**Issue by Diesfeldt** [mkshaw/r2mlm#64]
Thanks for the very nice module. When I run it, only one bargraph (number 5) is shown. How can I see each or all successive 5 barcharts?

**Comment by mkshaw** [comment]
Hi @Diesfeldt, in the View panel where you see the graphs (assuming you're using RStudio) you should be able to click left with the blue arrows to toggle the other bar graphs. Let me know if that works!
